server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#management:
#  tracing:
#    sampling:
#      probability: 1.0
spring:
    application:
      name: api-gateway
    cloud:
      gateway:
        routes:
          - id: queue-mgm
            uri: http://localhost:6001
            predicates:
              - Path=/**
          - id: crm
            uri: http://localhost:6002
            predicates:
              - Path=/**
logging:
  level:
    org.springframework.cloud: DEBUG
    reactor.netty: DEBUG
